## It is not ensured to work on Linux and Windows 
[general]
import = [
 "~/.config/alacritty/theme.toml"
]

[window]
opacity = 0.8

[font]
normal = {family = "FiraCode Nerd Font", style= "Retina"}

[terminal]
osc52 = "CopyPaste"
